
# esses comentarios sao para gerar o script de criacao do banco de dados

#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

spring.datasource.url=jdbc:postgresql://localhost:5433/SayuriDb
spring.datasource.username=postgres
spring.datasource.password=1234567

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update


api.url=${API_URL:https://auth.nuvemfiscal.com.br}

fiscal.id=${FISCAL_ID:de6KEYuEWgMmgPKrm9eB}
fiscal.secret=${FISCAL_SECRET:NIeOr34UIJfh8HlV9ErgpI2XU7B4C5tUDKuDP1V1}


security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}



security.jwt.duration=${JWT_DURATION:86400}
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200}


qz.private.key.path=./qz-private-key.pem
